default_config:

homeassistant:
  packages: !include_dir_named packages/

automation: !include automations.yaml
script: !include scripts.yaml

python_script:

frontend:
  themes: !include_dir_merge_named themes/

hacs:
  token: !secret hacs_token
  appdaemon: True
  python_script: True
  theme: True

rflink:
  port: /dev/ttyS0
  wait_for_ack: False