default_config:

homeassistant:
  packages: !include_dir_named packages/

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes/

rflink:
  port: /dev/ttyS0
  wait_for_ack: False