esphome:
  name: living_room_light
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: True

wifi:
  networks:
  - ssid: !secret ssid
    password: !secret password

logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: wifi_signal
    name: "Světlo obývák: signál"
    update_interval: 300s

output:
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: binary
    name: "Světlo obývák"
    output: relay

binary_sensor:
  - platform: status
    name: "Světlo obývák: status"

status_led:
  pin:
    number: GPIO13
    inverted: yes