recorder:
  purge_keep_days: 30
  db_url: !secret recorder_url

history:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - persistent_notification.invalid_config
      - sensor.time
      - sensor.mikrotik_uptime
      - sensor.teplota_procesoru
      - sensor.xiaomi_map
    domains:
      - group
      - updater
      - script
      - input_slider
      - automation
      - weather

logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.ram_use
      - sensor.cpu_use
      - sensor.clientraw_wind_direction
      - sensor.mikrotik_uptime
      - sensor.time
      - sensor.xiaomi_map
      - automation.zrcadleni_lampy_v_obyvaku
      - automation.zrcadleni_svetla_v_kumbalu
      - automation.zrcadleni_svetla_v_obyvaku
      - automation.vypnout_nocni_rezim
      - automation.zapnout_nocni_rezim
      - automation.zmena_teploty_v_obyvaku
      - automation.zmena_venkovni_teploty
    domains:
      - sun
      - updater
      - octoprint
      - media_player

logger:
 default: warning
 # logs:
    # homeassistant.components.mysensors: debug
    # mysensors.mysensors: debug
    # homeassistant.components.rflink: debug
    # custom_components.sensor.attributes: debug
    # homeassistant.components.device_tracker: debug
