recorder:
  purge_keep_days: 30

history:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - persistent_notification.invalid_config
    domains:
      - group
      - updater
      - script
      - input_slider
      - automation

logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.ram_use
      - sensor.cpu_use
      - media_player.spotify
      - sensor.clientraw_wind_direction
      - sensor.mikrotik_uptime
    domains:
      - sun
      - updater
      - octoprint

logger:
 default: warning
 # logs:
    # homeassistant.components.mysensors: debug
    # mysensors.mysensors: debug
    # homeassistant.components.rflink: debug
    # custom_components.sensor.attributes: debug
    # homeassistant.components.device_tracker: debug
