switch:
  - platform: mqtt
    name: "prusa_power"
    command_topic: "bedroom/relay/1/set"
    state_topic: "bedroom/relay/1"
    availability_topic: "nodered/status"
    payload_on: 1
    payload_off: 0
    payload_available: 1
    payload_not_available: 0
    optimistic: false
    qos: 1

octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_api
  bed: True
  number_of_tools: 1

sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error