speedtestdotnet:
  scan_interval:
    hours: 1

sensor:
  - platform: systemmonitor
    resources:
      - type: last_boot
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use

  - platform: command_line
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(2) }}'
    name: 'Teplota procesoru'
    scan_interval: 10

  - platform: rpi_power
    text_state: true

  - platform: template
    sensors:
      since_last_boot_templated:
        friendly_name: 'Poslední restart'
        icon_template: mdi:restore
        value_template: >-
          {%- set slb = states.sensor.last_boot.state.split(' ') -%}
          {%- set count = slb | length -%}
          {%- set hms = slb[count - 1] -%}
          {%- set hms_trimmed = hms.split('.')[0] -%}
          {%- set hms_split = hms_trimmed.split(':') -%}
          {%- set day = slb[0] | int -%}
          {%- set hours = hms_split[0] | int -%}
          {%- set minutes = hms_split[1] | int -%}
          {%- set seconds = hms_split[2] | int -%}
          {%- if count == 3 -%}
            {%- if day == 1 -%}
              1 den {{ ' ' }}
            {%- elif day > 1 and day < 5 -%}
              {{ day }} dny {{ ' ' }}
            {%- else -%}
              {{ day }} dnů {{ ' ' }}
            {%- endif -%}
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if hours == 1 -%}
              1 hodina
            {%- elif hours > 1 and hours < 5 -%}
              {{ hours }} hodiny
            {%- else -%}
              {{ hours }} hodin
            {%- endif -%}
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {%- if minutes == 1 -%}
              1 minuta
            {%- elif minutes > 1 and minutes < 5 -%}
              {{ minutes }} minuty
            {%- else -%}
              {{ minutes }} minut
            {%- endif -%}
          {%- endif -%}
          {%- if seconds > 0 -%}
            {%- if hours > 0 or minutes > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {%- if seconds == 1 -%}
              1 sekunda
            {%- elif seconds > 1 and seconds < 5 -%}
              {{ seconds }} sekundy
            {%- else -%}
              {{ seconds }} sekund
            {%- endif -%}
          {%- endif -%}
          